- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - ansible
      - anyenv
      - awscli
      - bat
      - fd
      - fzf
      - gh
      - ghq
      - git
      - graphviz
      - jq
      - lsd
      - mas
      - node
      - nvm
      - plantuml
      - pnpm
      - postgresql
      - procs
      - python3
      - ripgrep
      - sst
      - terraform
      - tig
      - tree
      - uv
      - wget
      - yarn
      - zsh

