# We can search packages by "brew search or website:https://formulae.brew.sh/cask/"
- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - 1password
      - alfred
      - appcleaner
      - chatgpt
      - claude
      - clipy
      - cursor
      - dbeaver-community
      - docker
      - google-chrome
      - loom
      - microsoft-edge
      - microsoft-remote-desktop
      - notion
      - obsidian
      - postman
      - slack
      - spectacle
      - typora
      - visual-studio-code
      - vivaldi
      - warp
      - zoom
